---
- version: "2"
- checks:
  method-complexity:
    enabled: true
  nested-control-flow:
    config:
      threshold: 6
#- plugins:
#  duplication:
#    config:
#      languages:
#        python:
#          python_version: 3
#  sonar-python:
#    checks:
#      python:S1542:
#        enabled: false
#      python:S3776:
#        enabled: false
#  pylint:
#    channel: beta
#    plugins:
#      - django
#    checks:
#      no-member:
#        enabled: false
#      import-error:
#        enabled: false
#  pep8:
#  #    enabled: true
#  fixme:
#    #    enabled: true
#    config:
#      strings:
#        - TOFIX
#        - TODO
#  csslint:
##    enabled: true
#
#exclude_patterns:
#  - "src/test.py"
