version: "2"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false
  pylint:
    channel: beta
    plugins:
      - django
    checks:
      no-member:
        enabled: false
      import-error:
        enabled: false
  pep8:
  fixme:
    config:
      strings:
        - TOFIX
        - TODO
  csslint:
    enabled: true

exclude_patterns:
  - "src/test.py"