version: "2"
checks:
  method-complexity:
    enabled: true
  nested-control-flow:
    config:
      threshold: 6
plugins:
  duplication:
    #    enabled: true
    config:
      languages:
        python:
          python_version: 3
  sonar-python:
    #    enabled: true
    checks:
      python:S1542:
        enabled: false
      python:S3776:
        enabled: false
  pylint:
    #    enabled: true
    channel: beta
    plugins:
      - django
    checks:
      no-member:
        enabled: false
      import-error:
        enabled: false
  pep8:
  #    enabled: true
  fixme:
    #    enabled: true
    config:
      strings:
        - TOFIX
        - TODO
  csslint:
#    enabled: true

exclude_patterns:
  - "src/test.py"


[flake8]
exclude =
    .*/,
    __pycache__/,
    .pytest_cache/,
    helm-chart/,
    */migrations/
ignore = E401, W605
max-line-length = 150

[pep8]
exclude =
    .*/,
    __pycache__/,
    .pytest_cache/,
    helm-chart/,
    */migrations/
ignore = E401, W605
max-line-length = 150

[pycodestyle]
exclude =
    .*/,
    __pycache__/,
    .pytest_cache/,
    helm-chart/,
    */migrations/
ignore = E401, W605
max-line-length = 150
