version: "2"
checks:
  method-complexity:
    enabled: false
  nested-control-flow:
    config:
      threshold: 6
plugins:
  duplication:
    enabled: false
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false
      python:S3776:
        enabled: false #TODO: Complexity to 20
  pylint:
    channel: beta
    plugins:
      - django
    checks:
      no-member:
        enabled: false
      import-error:
        enabled: false
  fixme:
    config:
      strings:
        - TOFIX
        - TODO
  csslint:
    enabled: true

exclude_patterns:
  - "src/test.py"