name: Build & Test Docker Image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chartboard:test
    - uses: actions/checkout@v1
    - name: Unit Test inside docker
      run: docker run --entrypoint=python chartboard:test src/manage.py test
