# thanks to @zhulik for https://github.com/zhulik/redis-action
name: Quality Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 2
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide, but pycharm is not :D
        flake8 . --count --max-complexity=10 --max-line-length=150 --statistics --ignore=E401,W605
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile-dev --tag chartboard:test
    - uses: actions/checkout@v1
    - name: Unit Test inside docker
      run: docker run --entrypoint=python chartboard:test src/manage.py test